import AppKit
import Testing
@testable import Qpaste
@testable import QpasteCore

@Suite("后台采集和图片", .serialized)
@MainActor
struct BackgroundCaptureTests {
    private func fixture(_ body: (HistoryStore, NSPasteboard) async throws -> Void) async throws {
        let name = "qpaste-background-\(UUID())"
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent(name)
        let defaults = UserDefaults(suiteName: name)!
        let settings = AppSettings(defaults: defaults)
        settings.maximumCount = 0; settings.retentionDays = 0
        let store = try HistoryStore(settings: settings, directory: directory)
        let board = NSPasteboard(name: .init(name))
        defer { store.flush(); board.releaseGlobally(); defaults.removePersistentDomain(forName: name); try? FileManager.default.removeItem(at: directory) }
        try await body(store, board)
    }

    @Test func blockedDecoderDoesNotBlockMainAndStopFlushesCapturesInOrder() async throws {
        try await fixture { store, board in
            let gate = DispatchSemaphore(value: 0)
            let monitor = ClipboardMonitor(store: store, pasteboard: board, decode: { snapshot in
                #expect(!Thread.isMainThread)
                gate.wait()
                return try ClipboardMonitor.decodeSnapshot(snapshot)
            })
            defer { for _ in 0..<3 { gate.signal() }; monitor.stop() }
            for text in ["first", "second", "first"] {
                board.clearContents(); board.setString(text, forType: .string)
                monitor.poll()
            }
            #expect(store.entries.isEmpty) // poll returned while the worker is blocked.
            for _ in 0..<3 { gate.signal() }
            monitor.stop() // Drain accepted writes and apply failures before termination.
            let page = try store.repository.page()
            #expect(page.entries.map(\.text) == ["first", "second"])
            let first = try #require(page.entries.first)
            #expect(try store.repository.copyEvents(for: first.id).count == 2)
            try await settle(store, count: 2)
            #expect(store.selectedItem != nil)
        }
    }

    @Test func deletionAndClearWinOverOlderSnapshots() async throws {
        try await fixture { store, board in
            let captured = try ClipboardMonitor.captureText("delete me", richData: nil, sourceName: "test", sourceBundleID: nil)
            let original = try #require(captured).entry
            store.add(original)
            try await settle(store, count: 1)
            let gate = DispatchSemaphore(value: 0)
            let monitor = ClipboardMonitor(store: store, pasteboard: board, decode: { snapshot in
                gate.wait(); return try ClipboardMonitor.decodeSnapshot(snapshot)
            })
            defer { gate.signal(); gate.signal(); monitor.stop() }
            board.clearContents(); board.setString("delete me", forType: .string)
            monitor.poll()
            store.delete(try #require(store.selectedItem))
            gate.signal(); monitor.stop()
            #expect(try store.repository.page().entries.isEmpty)
            board.clearContents(); board.setString("clear me", forType: .string)
            monitor.poll()
            store.clearHistory()
            gate.signal(); monitor.stop()
            #expect(try store.repository.page().entries.isEmpty)
            try await settle(store, count: 0)
        }
    }

    @Test func imageCapturePreviewAndPastePreserveOriginalData() async throws {
        try await fixture { store, board in
            let bitmap = try #require(NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: 800, pixelsHigh: 600,
                bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
                colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0))
            memset(try #require(bitmap.bitmapData), 180, bitmap.bytesPerRow * bitmap.pixelsHigh)
            let png = try #require(bitmap.representation(using: .png, properties: [:]))
            let monitor = ClipboardMonitor(store: store, pasteboard: board)
            defer { monitor.stop() }
            board.clearContents(); board.setData(png, forType: .png)
            let expected = try ClipboardMonitor.capture(from: board, sourceName: "test", sourceBundleID: nil)
            monitor.poll()
            monitor.stop()
            try await settle(store, count: 1)
            let item = try #require(store.selectedItem)
            #expect(item.imageWidth == 800 && item.imageHeight == 600)
            #expect(store.thumbnail(for: item) != nil) // Generated by the capture worker.
            let entry = try await store.content(for: item)
            #expect(entry.fingerprint == expected?.entry.fingerprint)
            let image = try await store.loadPreviewImage(for: item)
            #expect(image != nil && !store.isLoadingPreview(for: item))
            #expect(store.previewImage(for: item) === image)
            try await monitor.writeAsync(entry, plainText: false)
            #expect(board.data(forType: .png) == expected?.imageData)
            #expect(board.data(forType: .tiff) != nil)
            monitor.poll(); monitor.stop()
            #expect(try store.repository.page().totalCount == 1)
        }
    }

    @Test func failedCapturesRetryWithoutDuplicateRowsOrEvents() async throws {
        try await fixture { store, board in
            let db = try SQLiteDatabase(url: store.repository.databaseURL)
            try db.execute("CREATE TRIGGER fail_capture BEFORE INSERT ON entries BEGIN SELECT RAISE(FAIL,'test failure'); END")
            let monitor = ClipboardMonitor(store: store, pasteboard: board)
            defer { monitor.stop() }
            for _ in 0..<2 {
                board.clearContents(); board.setString("retry captured text", forType: .string)
                monitor.poll(); monitor.stop()
            }
            #expect(store.storageError != nil)
            #expect(try store.repository.page().entries.isEmpty)
            try db.execute("DROP TRIGGER fail_capture")
            store.flush()
            let page = try store.repository.page()
            #expect(page.totalCount == 1)
            let entry = try #require(page.entries.first)
            #expect(try store.repository.copyEvents(for: entry.id).count == 2)
            #expect(store.storageError == nil)
        }
    }

    @Test func decodedImageCacheKeepsRecentImagesWithinBudget() {
        let cache = ImageMemoryCache(maximumBytes: 2 * 40 * 40 * 4)
        let a = NSImage(size: NSSize(width: 40, height: 40))
        let b = NSImage(size: NSSize(width: 40, height: 40))
        let c = NSImage(size: NSSize(width: 40, height: 40))
        cache.insert(a, for: "a"); cache.insert(b, for: "b")
        #expect(cache.value(for: "a") === a)
        cache.insert(c, for: "c")
        #expect(cache.value(for: "b") == nil)
        #expect(cache.value(for: "a") === a && cache.value(for: "c") === c)
        #expect(cache.byteCount <= cache.maximumBytes)
        cache.insert(NSImage(size: NSSize(width: 200, height: 200)), for: "large")
        #expect(cache.value(for: "large") == nil && cache.byteCount <= cache.maximumBytes)
    }

    private func settle(_ store: HistoryStore, count: Int) async throws {
        for _ in 0..<300 {
            if store.entries.count == count && !store.isLoading && !store.isLoadingContent { return }
            try await Task.sleep(for: .milliseconds(10))
        }
        try #require(store.entries.count == count && !store.isLoading && !store.isLoadingContent)
    }
}
